### ISSUE TITLE
baselines/vcl is identical to vcl/ddm?

### ISSUE THREAD

**Issue by thangbui** [timrudner/S-FSVI#2]
Hi Tim,

Thanks for sharing the code - look forward to using it. Just checking if the vcl code under baselines/vcl is the same as in this [repo](https://github.com/nvcuong/variational-continual-learning/tree/master/ddm)? If yes, perhaps baselines/vcl should be a git submodule, or it should include an ack and link to the original repo.

Cheers,
Thang

**Comment by timrudner** [comment]
Hi Thang,

Thank you so much for your message!

This was an oversight on our part---thanks for pointing this out! We've added an acknowledgement as well as details about which code in the baseline directory is new or was modified.

Best,
Tim
